rate limiter added

diff --git a/.github/workflows/delpoy.yaml b/.github/workflows/delpoy.yaml
--- a/.github/workflows/delpoy.yaml
+++ b/.github/workflows/delpoy.yaml
@@ -36,8 +36,24 @@ jobs:
             fi
             docker run -d -p 80:3000 \
               --name my-app \
+              --network my-network \
               -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
               -e ENCRYPTION_PASSWORD=${{ secrets.ENCRYPTION_PASSWORD }} \
               -e HOST=${{ secrets.HOST }} \
+              -e REDIS_HOST=${{ secrets.REDIS_HOST }} \
               ${{ secrets.DOCKER_USERNAME }}/my-app:latest
           EOF
+      - name: Test Deployment
+        run: |
+          echo "Waiting for the application to be ready..."
+          sleep 10  # Wait for 10 seconds to allow the app to initialize
+
+          response=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.EC2_PUBLIC_IP }}/health)
+          echo "Received response code: $response"
+
+          if [ "$response" -ne 200 ]; then
+            echo "Health check failed with status code: $response"
+            exit 1
+          else
+            echo "Health check passed."
+          fi
